services:
  database:
    # MySQL
    image: mysql:latest
    container_name: rethink-corporation
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: rethink-ecommerce
      MYSQL_USER: rethinkadmin
      MYSQL_PASSWORD: rethinkadmin
    ports:
      - "3344:3306"
    volumes:
      - db_data:/var/lib/mysql\
  mail-dev:
    container_name: rethink-mail-dev
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"

volumes:
  db_data: