spring:
  datasource:
    url: jdbc:mysql://localhost:3344/rethink-ecommerce
    username: rethinkadmin
    password: rethinkadmin
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: localhost
    port: 1025
    username: rethinkadmin
    password: rethinkadmin
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable:true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

  application:
    security:
      jwt:
        secret-key: danhcutedanhcutedanhcutedanhcutedanhcutedanhcutedanhcutedanhcute
        expiration: 30000
        refresh-token:
          expiration: 604800000 #7 days
      mailling:
        frontend:
          activation-url: http://localhost:5173/auth/activate-account
          password-changing-url: http://localhost:5173/auth/change-password